import { CirclePlus, CircleX, Pencil } from 'lucide-react';
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { PageHeader } from '../components/ui';
import { ROUTES } from '../constants';

type Ingredient = { raw: string; material: string; inclusion: string };
const standardFields = ['DM %', 'CP %', 'ME (Mcal/Kg)', 'GE (Mcal/Kg)', 'EE %', 'CF %', 'TDN %', 'NDF %', 'ADF %', 'Ash %', 'Ca %', 'P %'];
const initialIngredients: Ingredient[] = Array.from({ length: 4 }, () => ({ raw: '33', material: 'Growth Max 30kg', inclusion: '1' }));

export default function AddFormula() { const navigate = useNavigate(); const [ingredients, setIngredients] = useState(initialIngredients); const [values, setValues] = useState<Record<string, string>>({}); const [product, setProduct] = useState(''); const setValue = (key: string, value: string) => setValues((v) => ({ ...v, [key]: value })); const update = (i: number, key: keyof Ingredient, value: string) => setIngredients((list) => list.map((row, index) => index === i ? { ...row, [key]: value } : row)); const add = () => setIngredients((list) => [...list, { raw: '33', material: 'Growth Max 30kg', inclusion: '1' }]); const remove = (i: number) => setIngredients((list) => list.filter((_, index) => index !== i)); const save = (e: React.FormEvent) => { e.preventDefault(); localStorage.setItem('titan_formula_draft', JSON.stringify({ product, values, ingredients })); navigate(ROUTES.FORMULAS); };
  return <><PageHeader title="ADD FORMULA" /><form onSubmit={save}><label className="formula-product">Product<select required value={product} onChange={(e) => setProduct(e.target.value)}><option value="">Select The Products</option><option>Growth Max</option><option>Care Max</option><option>Maintaince</option></select></label><h3 className="sectiontitle">Formula Standard</h3><div className="formula-standard">{standardFields.map((field) => <label key={field}>{field}<input value={values[field] || ''} onChange={(e) => setValue(field, e.target.value)} placeholder={field.startsWith('ME') ? 'Enter ME' : field.startsWith('GE') ? 'Enter GE' : `Enter ${field}`} /></label>)}</div><h3 className="sectiontitle">Ingredients</h3><div className="tablewrap ingredients-table"><table><thead><tr><th>Sr no.</th><th>Raw Materi</th><th>Material</th><th>Inclusion</th><th /></tr></thead><tbody>{ingredients.map((row, i) => <tr key={i}><td>1</td><td>{row.raw}</td><td>{row.material}</td><td>{row.inclusion}</td><td><button type="button" className="ingredient-remove" onClick={() => remove(i)}><CircleX /></button><button type="button" className="ingredient-edit"><Pencil /></button></td></tr>)}<tr className="ingredient-input"><td>{ingredients.length + 1}</td><td><input value="33" readOnly /></td><td><select value={ingredients[ingredients.length - 1]?.material || 'Growth Max 30kg'} onChange={(e) => setIngredients((list) => list.map((row, i) => i === list.length - 1 ? { ...row, material: e.target.value } : row))}><option>Growth Max 30kg</option><option>Soyabean Meal</option></select></td><td><input value="1" readOnly /></td><td><button type="button" className="ingredient-add" onClick={add}><CirclePlus /></button></td></tr></tbody></table></div><button className="btn orange formsubmit">Save Formula</button></form></>; }
