import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { PageHeader } from '../components/ui';
import { ROUTES } from '../constants';
import { readBrands, readProducts } from '../utils/catalog';

export default function AddVariant() {
  const navigate = useNavigate(); const brands = readBrands(); const products = readProducts(); const productNames = Array.from(new Set(products.map((item) => item.name).filter(Boolean)));
  const [name, setName] = useState(''); const [code, setCode] = useState(''); const [brand, setBrand] = useState(brands[0] || 'Titan Feeds'); const [product, setProduct] = useState(productNames[0] || 'Growth Max'); const [uom, setUom] = useState('Bag'); const [weight, setWeight] = useState(''); const [description, setDescription] = useState('');
  const submit = (e: React.FormEvent) => { e.preventDefault(); let rows: unknown = []; try { rows = JSON.parse(localStorage.getItem('titan_products_v4') || '[]'); } catch { /* start with empty catalogue */ } const list = Array.isArray(rows) && (rows.length === 0 || rows.every((row) => Array.isArray(row) && row.length >= 7)) ? rows as string[][] : []; list.push([brand, product, name, code, uom, weight ? `${weight}KG` : '', description || '-']); localStorage.setItem('titan_products_v4', JSON.stringify(list)); navigate(ROUTES.PRODUCTS); };
  return <><PageHeader title="ADD VARIANT" subtitle="Define product variations and specifications" actions={<button className="btn orange" onClick={() => navigate(ROUTES.PRODUCTS)}>List</button>} /><form className="product-form" onSubmit={submit}><label>Name<input required value={name} onChange={(e) => setName(e.target.value)} placeholder="Enter Name" /></label><label>Item Code<input required value={code} onChange={(e) => setCode(e.target.value)} placeholder="Enter Item Code" /></label><label>Brand<select value={brand} onChange={(e) => setBrand(e.target.value)}>{brands.map((item) => <option key={item}>{item}</option>)}</select></label><label>Product<select value={product} onChange={(e) => setProduct(e.target.value)}>{productNames.map((item) => <option key={item}>{item}</option>)}</select></label><label>UOM<select value={uom} onChange={(e) => setUom(e.target.value)}><option>Bag</option><option>KG</option></select></label><label>Weight In KG<input required value={weight} onChange={(e) => setWeight(e.target.value)} placeholder="Enter Weight In Kg" /></label><label className="full">Description<textarea value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Enter Description" /></label><button className="btn orange formsubmit">Add Variant</button></form></>;
}
