import{useEffect,useRef,useState}from'react';
import{Camera,CheckCircle2,Mail,Phone,MapPin,Briefcase,Shield,UserRound}from'lucide-react';
import { PageHeader } from '../components/ui';

type ProfileData={name:string,email:string,phone:string,role:string,department:string,address:string,bio:string,avatar:string};
const defaults:ProfileData={name:'Admin User',email:'admin@titan.com',phone:'',role:'Administrator',department:'Management',address:'',bio:'',avatar:''};
export default function Profile(){
 const[data,setData]=useState<ProfileData>(()=>({...defaults,...JSON.parse(localStorage.getItem('titan_profile')||'{}')}));
 const[saved,setSaved]=useState(false);const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{if(saved){const t=setTimeout(()=>setSaved(false),2500);return()=>clearTimeout(t)}},[saved]);
 const change=(k:keyof ProfileData,v:string)=>setData(d=>({...d,[k]:v}));
 const save=(e:React.FormEvent)=>{e.preventDefault();localStorage.setItem('titan_profile',JSON.stringify(data));setSaved(true)};
 const pick=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;if(f.size>2*1024*1024){alert('Please choose an image smaller than 2MB.');return}const r=new FileReader();r.onload=()=>change('avatar',String(r.result));r.readAsDataURL(f)};
 return <div className="profile-page"><PageHeader title="My Profile" subtitle="Manage your personal information and account details"/>{saved&&<div className="success-toast"><CheckCircle2/>Profile updated successfully</div>}<div className="profile-grid"><aside className="profile-card"><div className="avatar-large">{data.avatar?<img src={data.avatar}/>:<span>{(data.name||'A').slice(0,1).toUpperCase()}</span>}<button onClick={()=>fileRef.current?.click()} aria-label="Change profile photo"><Camera/></button><input ref={fileRef} type="file" accept="image/*" onChange={pick} hidden/></div><h2>{data.name||'Admin User'}</h2><p>{data.role}</p><div className="profile-meta"><span><Mail/>{data.email||'—'}</span><span><Phone/>{data.phone||'Not added'}</span><span><Briefcase/>{data.department||'Not added'}</span></div><small>JPG, PNG or WEBP. Maximum 2MB.</small></aside><form className="profile-form-card" onSubmit={save}><div className="form-section-title"><UserRound/><div><h3>Personal Information</h3><p>Update your basic profile details</p></div></div><div className="formgrid"><label><span>Full Name</span><input required value={data.name} onChange={e=>change('name',e.target.value)} placeholder="Enter full name"/></label><label><span>Email Address</span><input required type="email" value={data.email} onChange={e=>change('email',e.target.value)} placeholder="Enter email address"/></label><label><span>Phone Number</span><input value={data.phone} onChange={e=>change('phone',e.target.value)} placeholder="Enter phone number"/></label><label><span>Role</span><input value={data.role} onChange={e=>change('role',e.target.value)} placeholder="Enter role"/></label><label><span>Department</span><input value={data.department} onChange={e=>change('department',e.target.value)} placeholder="Enter department"/></label><label><span>Address</span><input value={data.address} onChange={e=>change('address',e.target.value)} placeholder="Enter address"/></label><label className="full"><span>About / Bio</span><textarea value={data.bio} onChange={e=>change('bio',e.target.value)} placeholder="Write a short profile description"/></label></div><div className="security-note"><Shield/><div><strong>Account Security</strong><p>Your profile is stored locally in this frontend demo. Backend authentication can be connected later.</p></div></div><div className="profile-actions"><button type="button" className="btn light" onClick={()=>setData({...defaults,...JSON.parse(localStorage.getItem('titan_profile')||'{}')})}>Reset</button><button className="btn orange">Save Changes</button></div></form></div></div>
}
